set(CMAKE_BUILD_TYPE "RelWithDebInfo" CACHE STRING "")

set(CMAKE_INSTALL_PREFIX "../stage" CACHE PATH "")

set(Boost_USE_STATIC_LIBS ON CACHE BOOL "")
set(BOOST_ROOT "${CMAKE_CURRENT_LIST_DIR}/boost_1_57_0" CACHE PATH "")

set(ZLIB_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/zlib-1.2.8/stage/include" CACHE PATH "")
set(ZLIB_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/zlib-1.2.8/stage/lib/zlibstatic.lib" CACHE FILEPATH "")

set(HDF5_BUILD_CPP_LIB ON CACHE BOOL "")
set(HDF5_ENABLE_Z_LIB_SUPPORT ON CACHE BOOL "")
set(HDF5_DIR "${CMAKE_CURRENT_LIST_DIR}/hdf5-1.8.14/stage/cmake/hdf5" CACHE PATH "")

set(PNG_PNG_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/lpng1615/stage/include" CACHE PATH "")
set(PNG_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/lpng1615/stage/lib/libpng16_static.lib" CACHE FILEPATH "")

set(OSGEO4W_ROOT "${CMAKE_CURRENT_LIST_DIR}/spatialindex-src-1.8.5/stage" CACHE PATH "")

