string(TOLOWER "$ENV{SEAMASS_BUILD}" SEAMASS_BUILD)
set(CMAKE_BUILD_TYPE "${SEAMASS_BUILD}" CACHE STRING "")

set(CMAKE_INSTALL_PREFIX "../../../install/$ENV{SEAMASS_TOOLSET}/${SEAMASS_BUILD}" CACHE PATH "")

set(Boost_USE_STATIC_LIBS ON CACHE BOOL "")
set(BOOST_ROOT "${CMAKE_CURRENT_LIST_DIR}/src/boost_1_57_0" CACHE PATH "")
set(BOOST_LIBRARYDIR "${CMAKE_CURRENT_LIST_DIR}/install/$ENV{SEAMASS_TOOLSET}/boost/lib" CACHE PATH "")

set(ZLIB_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/install/$ENV{SEAMASS_TOOLSET}/zlib/${SEAMASS_BUILD}/include" CACHE PATH "")
if(SEAMASS_BUILD STREQUAL "debug")
	set(ZLIB_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/install/$ENV{SEAMASS_TOOLSET}/zlib/${SEAMASS_BUILD}/lib/zlibstaticd.lib" CACHE FILEPATH "")
else(SEAMASS_BUILD STREQUAL "debug")
	set(ZLIB_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/install/$ENV{SEAMASS_TOOLSET}/zlib/${SEAMASS_BUILD}/lib/zlibstatic.lib" CACHE FILEPATH "")
endif(SEAMASS_BUILD STREQUAL "debug")

set(CURL_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/install/$ENV{SEAMASS_TOOLSET}/curl/${SEAMASS_BUILD}/include" CACHE PATH "")
if(SEAMASS_BUILD STREQUAL "debug")
	set(CURL_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/install/$ENV{SEAMASS_TOOLSET}/curl/${SEAMASS_BUILD}/lib/libcurl_a_debug.lib" CACHE FILEPATH "")
else(SEAMASS_BUILD STREQUAL "debug")
	set(CURL_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/install/$ENV{SEAMASS_TOOLSET}/curl/${SEAMASS_BUILD}/lib/libcurl_a.lib" CACHE FILEPATH "")
endif(SEAMASS_BUILD STREQUAL "debug")

set(PNG_PNG_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/install/$ENV{SEAMASS_TOOLSET}/lpng/${SEAMASS_BUILD}/include" CACHE PATH "")
if(SEAMASS_BUILD STREQUAL "debug")
	set(PNG_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/install/$ENV{SEAMASS_TOOLSET}/lpng/${SEAMASS_BUILD}/lib/libpng15_staticd.lib" CACHE FILEPATH "")
else(SEAMASS_BUILD STREQUAL "debug")
	set(PNG_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/install/$ENV{SEAMASS_TOOLSET}/lpng/${SEAMASS_BUILD}/lib/libpng15_static.lib" CACHE FILEPATH "")
endif(SEAMASS_BUILD STREQUAL "debug")

set(HDF5_BUILD_CPP_LIB ON CACHE BOOL "")
set(HDF5_ENABLE_Z_LIB_SUPPORT ON CACHE BOOL "")
set(HDF5_BUILD_HL_LIB ON CACHE BOOL "")
set(HDF5_BUILD_TOOLS ON CACHE BOOL "")
set(HDF5_DIR "${CMAKE_CURRENT_LIST_DIR}/install/$ENV{SEAMASS_TOOLSET}/hdf5/${SEAMASS_BUILD}/cmake/hdf5" CACHE PATH "")

set(NC_EXTRA_DEPS "ws2_32 wldap32" CACHE PATH "")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "")
set(netCDF_DIR "${CMAKE_CURRENT_LIST_DIR}/install/$ENV{SEAMASS_TOOLSET}/netcdf-c/${SEAMASS_BUILD}/lib/cmake/netCDF" CACHE PATH "")
             
set(OSGEO4W_ROOT "${CMAKE_CURRENT_LIST_DIR}/install/$ENV{SEAMASS_TOOLSET}/spatialindex/${SEAMASS_BUILD}" CACHE PATH "")

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_LIST_DIR}/src/eigen-3.2.2/cmake" CACHE PATH "")
set(EIGEN3_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/src/eigen-3.2.2" CACHE PATH "")

set(PugiXML_DIR "${CMAKE_CURRENT_LIST_DIR}/install/$ENV{SEAMASS_TOOLSET}/pugixml/${SEAMASS_BUILD}/lib/cmake/pugixml" CACHE PATH "")
