set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "")

set(CMAKE_INSTALL_PREFIX "../debug" CACHE PATH "")

set(Boost_USE_STATIC_LIBS ON CACHE BOOL "")
set(BOOST_ROOT "${CMAKE_CURRENT_LIST_DIR}/boost_1_57_0" CACHE PATH "")

set(ZLIB_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/zlib-1.2.8/debug/include" CACHE PATH "")
set(ZLIB_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/zlib-1.2.8/debug/lib/zlibstaticd.lib" CACHE FILEPATH "")

set(HDF5_BUILD_CPP_LIB ON CACHE BOOL "")
set(HDF5_ENABLE_Z_LIB_SUPPORT ON CACHE BOOL "")
set(HDF5_DIR "${CMAKE_CURRENT_LIST_DIR}/hdf5-1.8.14/debug/cmake/hdf5" CACHE PATH "")

set(PNG_PNG_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/lpng1615/debug/include" CACHE PATH "")
set(PNG_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/lpng1615/debug/lib/libpng16_staticd.lib" CACHE FILEPATH "")

set(OSGEO4W_ROOT "${CMAKE_CURRENT_LIST_DIR}/spatialindex-src-1.8.5/debug" CACHE PATH "")

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_LIST_DIR}/eigen-3.2.2/cmake" CACHE PATH "")
set(EIGEN3_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/eigen-3.2.2" CACHE PATH "")



